# Generated by Django 6.0 on 2025-12-13 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.test'),
        ),
    ]
