# Generated by Django 6.0 on 2025-12-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Balansni to'ldirish", max_length=100)),
                ('user_label', models.CharField(default='Foydalanuvchi:', max_length=100)),
                ('card_label', models.CharField(default="To'lov uchun karta raqami:", max_length=100)),
                ('card_number', models.CharField(default='8600 1234 5678 9012', max_length=20)),
                ('card_type', models.CharField(default='Humo / UzCard', max_length=50)),
                ('admin_label', models.CharField(default="Admin bilan bog'lanish:", max_length=100)),
                ('admin_telegram', models.CharField(default='@biotron_admin', max_length=100)),
                ('admin_telegram_link', models.URLField(default='https://t.me/biotron_admin')),
                ('instruction_title', models.CharField(default="✅ To'lovni tasdiqlash:", max_length=100)),
                ('instruction_text', models.TextField(default="1. Yuqoridagi karta raqamiga kerakli summani o'tkazing.<br>\n2. <strong>To'lov chekining (skrinshot) rasm</strong>ni yuqoridagi Telegram admin @biotron_admin ga yuboring.<br>\n3. Balans 5 daqiqada hisobingizga qo'shiladi.")),
            ],
            options={
                'verbose_name': "To'lov sozlamasi",
                'verbose_name_plural': "To'lov sozlamalari",
            },
        ),
    ]
